era_website/config/routes.rb
Rails.application.routes.draw do

	get	'/login', to: 'session#new'
	post	'/login', to: 'sessions#create'
	delete	'/logout', to: 'sessions#destroy'
        get 'sessions/new'

	
	get 'welcome/index'

	
resources :govtusers	
	resources :organizations
	resources :civilusers

	resources :disasterevents
	resources :disasterevents do

		resources :resourceitems

	end
	root 'welcome#index'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

era_website/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
	def index
  
	
	end

end

era_website/app/helpers/welcome_helper.rb
module WelcomeHelper
end

era_website/app/views/welcome/index.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}

body {
    font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}

nav {
    float: left;
    width: 30%;
    height: 400px;
    background: #ccc;
    padding: 20px;
}

nav ul {
    list-style-type: none;
    padding: 20px;
}

article {
    float: left;
    padding: 20px;
    width: 70%;
    background-color: #f1f1f1;
    height: 400px; 
}

section:after {
    content: "";
    display: table;
    clear: both;
}

footer {
    background-color: #0000cc;
    padding: 10px;
    text-align: center;
    color: white;
    height: 400px;
}

@media (max-width: 600px) {
    nav, article {
        width: 100%;
        heigh: auto;
    }
}
</style>
</head>
<body>


<header>
    <h1>Emergency Resource Allocation Website</h1>
    <h2>(E.R.A. Website)</h2>

</header>


<section>
<h4>
  <nav>
    <ul>
     <!-- <li><%= link_to 'Disaster index', controller: 'disasterevents' %></li><br> -->
     <!-- <li><%= link_to 'All Government Users', controller: 'govtusers' %></li><br> -->
     <!-- <li><%= link_to 'Show all Government Organizations', controller: 'organizations' %></li> -->
  <li><%= link_to 'Sign Up', new_govtuser_path %></li><br><hr>
     
      <li><%= link_to 'Login', sessions_new_path %></li><br>

<!--      <li><%= link_to 'Civilian User Login', sessions_new_path %></li><br>-->
    </ul>
  </nav>
</h4>

  <article>
	<h2>Purpose:<h2>
	<h4><p>
		The Emergency Resource Allocation Website is intended to 
		help with rescue efforts in the event of a disaster. 
		This website will allow government programs like FEMA to 
		better analyze the aftermath of a disaster. This website 
		will show the user what regions need what resources, what 
		the rescue efforts' total resources are and allow civilians
		to report what resources are needed in their area. 
	</p>
</h4>
  </article>
</section>

<footer>
  <p></p>
</footer>

</body>
</html>