era_website/config/routes.rb
Rails.application.routes.draw do

	get	'/login', to: 'session#new'
	post	'/login', to: 'sessions#create'
	delete	'/logout', to: 'sessions#destroy'
        get 'sessions/new'

	
	get 'welcome/index'

	
resources :govtusers	
	resources :organizations
	resources :civilusers

	resources :disasterevents
	resources :disasterevents do

		resources :resourceitems

	end
	root 'welcome#index'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

era_website/app/models/civiluser.rb
class Civiluser < ApplicationRecord

	validates :username, confirmation: { message: "does not match username"}
	validates :username_confirmation, presence: true
	validates :username, uniqueness: true
	validates :password, confirmation: { message: "does not match password"}
	validates :password_confirmation, presence: true
	validates :phone_number, confirmation: { message: "does not match phone number"}
	validates :phone_number_confirmation, presence: true
	validates :first_name, :last_name, :city, :state, :username, :password, :email, :phone_number, presence: true

	has_secure_password
end

era_website/app/controllers/civilusers_controller.rb
class CivilusersController < ApplicationController

	def index
		@civilusers = Civiluser.all
	end
	
	def login
		@civiluser = Civiluser.find(params[:username])
	end
	
	def show
		@civiluser = Civiluser.find(params[:id])
	end
	
	def new
		@civiluser = Civiluser.new
	end
	
	def edit
		@civiluser = Civiluser.find(params[:id])
	end
	
	def create
		@civiluser = Civiluser.new(civiluser_params)
		
		if @civiluser.save
			log_in @civiluser
			flash[:success] = "Sign Up Success"
			redirect_to @civiluser
		else 
			render 'new'
		end
	end
	
	def update
		@civiluser = Civiluser.find(params[:id])
		
		if @civiluser.update(civiluser_params)
			redirect_to @civiluser
		else
			render 'edit'
		end
	end
	
	def destroy 
		@civiluser = Civiluser.find(params[:id])
		@civiluser.destroy
		
		redirect_to civilusers_path
	end
			
	private
		def civiluser_params
			params.require(:civiluser).permit(:first_name, :last_name, :address, :city, :state, :username, :username_confirmation, :password, :password_confirmation, :email, :phone_number, :phone_number_confirmation)
		end
end

era_website/app/helpers/civilusers_helper.rb
module CivilusersHelper
end

era_website/app/views/civilusers/_form.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
User Sign Up<hr>
</header>
<p style="text-align:center; font-size:20px; padding-top:10px;"><%= link_to 'Return to Welcome Page', controller: 'welcome' %></p>
<%= form_with model: @civiluser, local: true do |form| %>
   <% if @civiluser.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@civiluser.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @civiluser.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">

  <p class="ex1">
    <%= form.label :First_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p class="ex1">
    <%= form.label :Last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p class="ex1">
    <%= form.label :street_address %><br>
    <%= form.text_field :address %>
  </p>

  <p class="ex1">
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </p>	

  <p class="ex1">
    <%= form.label :State %><br>
    <%= form.select(:state, [['Alabama','Alabama'],['Alaska', 'Alaska'],['Arizona','Arizona'],['Arkansas','Arkansas'],['California','California'],['Colorado', 'Colorado'],['Connecticut','Connecticut'],['Delaware','Delaware'],['Florida','Florida'],['Georgia','Georgia'],['Hawaii','Hawaii'],['Idaho','Idaho'],['Illinois','Illinois'],['Indiana','Indiana'],['Iowa','Iowa'],['Kansas','Kansas'],['Kentucky','Kentucky'],['Louisiana','Louisiana'],['Maine','Maine'],['Maryland','Maryland'],['Massachusetts','Massachusetts'],['Michigan','Michigan'],['Minnesota','Minnesota'],['Mississippi','Mississippi'],['Missouri','Missouri'],['Montana','Montana'],['Nebraska','Nebraska'],['Nevada','Nevada'],['New Hampshire','New Hampshire'],['New Jersey','New Jersey'],['New Mexico','New Mexico'],['New York','New York'],['North Carolina','North Carolina'],['North Dakota','North Dakota'],['Ohio','Ohio'],['Oklahoma','Oklahoma'],['Oregon','Oregon'],['Pennsylvania','Pennsylvania'],['Rhode Island','Rhode Island'],['South Carolina','South Carolina'],['South Dakota','South Dakota'],['Tennessee','Tennessee'],['Texas','Texas'],['Utah','Utah'],['Vermont','Vermont'],['Virginia','Virginia'],['Washington','Washington'],['West Virginia','West Virginia'],['Wisconsin','Wisconsin'],['Wyoming','Wyoming']]) %>
  </p>

    </div>
    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
 
	  <p class="ex1">
	    <%= form.label :Username %><br>
	    <%= form.text_field :username %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Confirm_Username %><br>
	    <%= form.text_field :username_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :Password %><br>
	    <%= form.password_field :password %>
	  </p>
	  
	  <p class="ex1">
	    <%= form.label :Confirm_Password %><br>
	    <%= form.password_field :password_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :email %><br>
	    <%= form.email_field :email, placeholder:"example@website.com" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number, placeholder:"Ex: 956456789" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number_confirmation, placeholder:"Ex: 956456789" %>
	  </p>
  	  <p class="ex1">
  	    <%= form.submit 'Save'%>
  	  </p>
    </div>
    <div class="col1"></div>

<% end %>
</div>
<footer> 
</footer>
</body>
</html>

era_website/app/views/civilusers/_form1.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
Edit Profile Information<hr>
</header>

<p style="text-align: center; font-size:20px; padding-top:10px;"><%= link_to 'Return to Profile', civiluser_path(@civiluser.id) %></p>

<%= form_with model: @civiluser, local: true do |form| %>
   <% if @civiluser.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@civiluser.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @civiluser.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">

  <p class="ex1">
    <%= form.label :First_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p class="ex1">
    <%= form.label :Last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p class="ex1">
    <%= form.label :street_address %><br>
    <%= form.text_field :address %>
  </p>

  <p class="ex1">
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </p>	

  <p class="ex1">
    <%= form.label :State %><br>
    <%= form.select(:state, [['Alabama','Alabama'],['Alaska', 'Alaska'],['Arizona','Arizona'],['Arkansas','Arkansas'],['California','California'],['Colorado', 'Colorado'],['Connecticut','Connecticut'],['Delaware','Delaware'],['Florida','Florida'],['Georgia','Georgia'],['Hawaii','Hawaii'],['Idaho','Idaho'],['Illinois','Illinois'],['Indiana','Indiana'],['Iowa','Iowa'],['Kansas','Kansas'],['Kentucky','Kentucky'],['Louisiana','Louisiana'],['Maine','Maine'],['Maryland','Maryland'],['Massachusetts','Massachusetts'],['Michigan','Michigan'],['Minnesota','Minnesota'],['Mississippi','Mississippi'],['Missouri','Missouri'],['Montana','Montana'],['Nebraska','Nebraska'],['Nevada','Nevada'],['New Hampshire','New Hampshire'],['New Jersey','New Jersey'],['New Mexico','New Mexico'],['New York','New York'],['North Carolina','North Carolina'],['North Dakota','North Dakota'],['Ohio','Ohio'],['Oklahoma','Oklahoma'],['Oregon','Oregon'],['Pennsylvania','Pennsylvania'],['Rhode Island','Rhode Island'],['South Carolina','South Carolina'],['South Dakota','South Dakota'],['Tennessee','Tennessee'],['Texas','Texas'],['Utah','Utah'],['Vermont','Vermont'],['Virginia','Virginia'],['Washington','Washington'],['West Virginia','West Virginia'],['Wisconsin','Wisconsin'],['Wyoming','Wyoming']]) %>
  </p>

    </div>
    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
 
	  <p class="ex1">
	    <%= form.label :Username %><br>
	    <%= form.text_field :username %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Confirm_Username %><br>
	    <%= form.text_field :username_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :Password %><br>
	    <%= form.password_field :password %>
	  </p>
	  
	  <p class="ex1">
	    <%= form.label :Confirm_Password %><br>
	    <%= form.password_field :password_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :email %><br>
	    <%= form.email_field :email, placeholder:"example@website.com" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number, placeholder:"Ex: 956456789" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number_confirmation, placeholder:"Ex: 956456789" %>
	  </p>
  	  <p class="ex1">
  	    <%= form.submit 'Update User'%>
  	  </p>
    </div>
    <div class="col1"></div>

<% end %>
</div>
<footer> 
</footer>
</body>
</html>

era_website/app/views/civilusers/edit.html.erb
<style> p.ex1 {padding-left: 20px;}</style>
<%= render 'form1' %>
<%= link_to 'Back to profile', civilusers_path(@civiluser) %>

era_website/app/views/civilusers/index.html.erb
<head>
<style>
table, th, td {
    border: 2px solid black;
    padding: 8px;
}
tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>
<h1 style="text-align:center"> All Civilian Users: Admin Use Only </h1>
<h4>
<p style="padding-left: 20px;">
<%= link_to 'Back to profile', govtuser_path(current_user) %><br>
</p>
<table align="center" style="width:95%">
  <tr>
    <th style="width:25%">Username</th>
    <th style="width:20%">Name</th>
    <th style="width:25%" colspan="3"></th> 
  </tr>
 
  <% @civilusers.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td style="text-align: center"><%= link_to 'Show', civiluser_path(user) %></td>
      <td style="text-align: center"><%= link_to 'Delete', civiluser_path(user),
				method: :delete,
				data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

</body>
</h4>

era_website/app/views/civilusers/login.html.erb
<% provide(:title, 'Login') %>
<h1>Login</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

era_website/app/views/civilusers/new.html.erb
<style> p.ex1 {padding-left: 20px;}</style>
<%= render 'form' %>
<p class="ex1"><%= link_to 'Return to Welcome Page', controller: 'welcome' %></p>

era_website/app/views/civilusers/show.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
Main Page<hr>
</header>

<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">
          <h3>Profile Information</h3>
          <ul>
            <li class="ex2"> <strong>Username: </strong><%= current_user.username %></li>
            <li class="ex2"> <strong>Name: </strong><%= @civiluser.first_name %> <%= @civiluser.last_name %></li>
            <li class="ex2"> <strong>Street Address: </strong><%= @civiluser.address %></li>
            <li class="ex2"> <strong>City: </strong><%= @civiluser.city %></li>
            <li class="ex2"> <strong>State: </strong><%= @civiluser.state %></li><hr>
            <li class="ex2"> <%= link_to 'View All Disasters', controller: 'disasterevents' %></li>
	    <li class="ex2"> <%= link_to 'Edit Profile', edit_civiluser_path(@civiluser) %></li>
	    <% if logged_in? %>
		<li class="ex2"> <%= link_to "Log out", logout_path, method: :delete %></li>
      	    <% end %>
          </ul>   
    </div>

    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
            <h3>Contact Information</h3>        
	      <strong>Email:</strong><%= @civiluser.email %><br>
	      <strong>Phone Number:</strong><%= @civiluser.phone_number %>
    </div>
    <div class="col1"></div>

</div>

<footer> 
</footer>
</body>
</html>
  