era_website/config/routes.rb
Rails.application.routes.draw do

	get	'/login', to: 'session#new'
	post	'/login', to: 'sessions#create'
	delete	'/logout', to: 'sessions#destroy'
        get 'sessions/new'

	
	get 'welcome/index'

	
resources :govtusers	
	resources :organizations
	resources :civilusers

	resources :disasterevents
	resources :disasterevents do

		resources :resourceitems

	end
	root 'welcome#index'

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

era_website/app/models/govtuser.rb
class Govtuser < ApplicationRecord
	validates :username, confirmation: { message: "does not match username"}
	validates :username_confirmation, presence: true
	validates :username, uniqueness: true
	validates :password, confirmation: { message: "does not match password"}
	validates :password_confirmation, presence: true
	validates :phone_number, confirmation: { message: "does not match phone number"}
	validates :phone_number_confirmation, presence: true
	validates :first_name, :last_name, :city, :state, :username, :password, :email, :phone_number, presence: true

	has_secure_password
end

era_website/app/controllers/govtusers_controller.rb
class GovtusersController < ApplicationController

	def index
		@govtusers = Govtuser.all	
	end
	
	def login
		@govtuser = Govtuser.find(params[:username])
	end
	
	def profile
		@govtuser = Govtuser.find(params[:id])		
	end

        def show
		@govtuser = Govtuser.find(params[:id])
	end

	def new
		@govtuser = Govtuser.new
	end

	def edit
		@govtuser = Govtuser.find(params[:id])
	end

	def create
		@govtuser = Govtuser.new(govtuser_params)
		
		if(@govtuser.usertype == "govt" )
		  if(Organization.where(orgname: @govtuser.orgname, orgcode: @govtuser.orgcode).exists? )
		  	  if @govtuser.save
		  	    log_in @govtuser
			    flash[:success] = "Saved Government User"
			    redirect_to @govtuser
			    puts "chicken"
			  else
				  flash[:danger] = "Did NOT save Government User"
			  	  render 'new'
			  end
		  else
			 flash[:danger] = "Government name and/or code not valid"
			 render 'new'
			 puts "beef"
		 end
	 	else
		 if @govtuser.save
		  	    log_in @govtuser
			    flash[:success] = "Saved Civilian User"
			    redirect_to @govtuser
		 else
			    flash[:danger] = "Did NOT save Civilian User"
			    render 'new'
	  	 end
		end
				
	end	

	def update
		@govtuser = Govtuser.find(params[:id])

		if @govtuser.update(govtuser_params)
    			redirect_to @govtuser
  		else
  			render 'edit'
  		end
	end	

	def destroy
		@govtuser = Govtuser.find(params[:id])
		@govtuser.destroy
		
		redirect_to govtusers_path
	end

	private
		def govtuser_params
			params.require(:govtuser).permit(:first_name, :last_name, :address, :city, :state, :username, :username_confirmation, :password, :password_confirmation, :email, :phone_number, :phone_number_confirmation, :usertype, :orgname, :orgcode)
		end
end

era_website/app/helpers/govtusers_helper.rb
module GovtusersHelper
end

era_website/app/views/govtusers/_form.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
New User Sign Up<hr>
</header>
<p style="text-align:center; font-size:20px; padding-top:10px;"><%= link_to 'Return to Welcome Page', controller: 'welcome' %></p>
<%= form_with model: @govtuser, local: true do |form| %>
   <% if @govtuser.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@govtuser.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @govtuser.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">

  <p class="ex1">
    <%= form.label :First_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p class="ex1">
    <%= form.label :Last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p class="ex1">
    <%= form.label :street_address %><br>
    <%= form.text_field :address %>
  </p>

  <p class="ex1">
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </p>	

  <p class="ex1">
    <%= form.label :State %><br>
    <%= form.select(:state, [['Alabama','Alabama'],['Alaska', 'Alaska'],['Arizona','Arizona'],['Arkansas','Arkansas'],['California','California'],['Colorado', 'Colorado'],['Connecticut','Connecticut'],['Delaware','Delaware'],['Florida','Florida'],['Georgia','Georgia'],['Hawaii','Hawaii'],['Idaho','Idaho'],['Illinois','Illinois'],['Indiana','Indiana'],['Iowa','Iowa'],['Kansas','Kansas'],['Kentucky','Kentucky'],['Louisiana','Louisiana'],['Maine','Maine'],['Maryland','Maryland'],['Massachusetts','Massachusetts'],['Michigan','Michigan'],['Minnesota','Minnesota'],['Mississippi','Mississippi'],['Missouri','Missouri'],['Montana','Montana'],['Nebraska','Nebraska'],['Nevada','Nevada'],['New Hampshire','New Hampshire'],['New Jersey','New Jersey'],['New Mexico','New Mexico'],['New York','New York'],['North Carolina','North Carolina'],['North Dakota','North Dakota'],['Ohio','Ohio'],['Oklahoma','Oklahoma'],['Oregon','Oregon'],['Pennsylvania','Pennsylvania'],['Rhode Island','Rhode Island'],['South Carolina','South Carolina'],['South Dakota','South Dakota'],['Tennessee','Tennessee'],['Texas','Texas'],['Utah','Utah'],['Vermont','Vermont'],['Virginia','Virginia'],['Washington','Washington'],['West Virginia','West Virginia'],['Wisconsin','Wisconsin'],['Wyoming','Wyoming']]) %>
  </p>

    </div>
    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
 
	  <p class="ex1">
	    <%= form.label :Username %><br>
	    <%= form.text_field :username %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Confirm_Username %><br>
	    <%= form.text_field :username_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :Password %><br>
	    <%= form.password_field :password %>
	  </p>
	  
	  <p class="ex1">
	    <%= form.label :Confirm_Password %><br>
	    <%= form.password_field :password_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :email %><br>
	    <%= form.email_field :email, placeholder:"example@website.com" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number, placeholder:"Ex: 956456789" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number_confirmation, placeholder:"Ex: 956456789" %>
	  
	  </p>


<p class="ex1">
<%= form.select(:usertype, [['Civilian', 'civil'],
                                  ['Government', 'govt'],
                                  
                                 ],{ :prompt => "Select User Type"},
                                   { :onchange => "choose_a_type()", :id => "myselect"}
                                 ) %>
  </p>

<p id="demo"></p>

<script type="text/javascript">
  function choose_a_type()
  {
	var x=  document.getElementById("myselect").value;
	if( x == "govt"){
		document.getElementById("govtStuff").style.display = "";
	}
	else { 	document.getElementById("govtStuff").style.display = "none";}
  }
</script>
		
          <p id="govtStuff" class="ex1" style="display:none">
	    <%= form.label :Organization_Name %><br>
	    <%= form.text_field :orgname, value: '' %>
	    <%= form.label :Organization_Code%><br>
	    <%= form.text_field :orgcode, value: '' %>
	  </p> 

  	  <p class="ex1">
  	    <%= form.submit 'Save'%>
  	  </p>
    </div>
    <div class="col1"></div>

<% end %>
</div>
<footer> 
</footer>
</body>
</html>

era_website/app/views/govtusers/_form1.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
Edit Profile Information<hr>
</header>

<p style="text-align: center; font-size:20px; padding-top:10px;"><%= link_to 'Return to Profile', govtuser_path(@govtuser.id) %></p>

<%= form_with model: @govtuser, local: true do |form| %>
   <% if @govtuser.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@govtuser.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @govtuser.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">

  <p class="ex1">
    <%= form.label :First_name %><br>
    <%= form.text_field :first_name %>
  </p>
 
  <p class="ex1">
    <%= form.label :Last_name %><br>
    <%= form.text_field :last_name %>
  </p>

  <p class="ex1">
    <%= form.label :street_address %><br>
    <%= form.text_field :address %>
  </p>

  <p class="ex1">
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </p>	

  <p class="ex1">
    <%= form.label :State %><br>
    <%= form.select(:state, [['Alabama','Alabama'],['Alaska', 'Alaska'],['Arizona','Arizona'],['Arkansas','Arkansas'],['California','California'],['Colorado', 'Colorado'],['Connecticut','Connecticut'],['Delaware','Delaware'],['Florida','Florida'],['Georgia','Georgia'],['Hawaii','Hawaii'],['Idaho','Idaho'],['Illinois','Illinois'],['Indiana','Indiana'],['Iowa','Iowa'],['Kansas','Kansas'],['Kentucky','Kentucky'],['Louisiana','Louisiana'],['Maine','Maine'],['Maryland','Maryland'],['Massachusetts','Massachusetts'],['Michigan','Michigan'],['Minnesota','Minnesota'],['Mississippi','Mississippi'],['Missouri','Missouri'],['Montana','Montana'],['Nebraska','Nebraska'],['Nevada','Nevada'],['New Hampshire','New Hampshire'],['New Jersey','New Jersey'],['New Mexico','New Mexico'],['New York','New York'],['North Carolina','North Carolina'],['North Dakota','North Dakota'],['Ohio','Ohio'],['Oklahoma','Oklahoma'],['Oregon','Oregon'],['Pennsylvania','Pennsylvania'],['Rhode Island','Rhode Island'],['South Carolina','South Carolina'],['South Dakota','South Dakota'],['Tennessee','Tennessee'],['Texas','Texas'],['Utah','Utah'],['Vermont','Vermont'],['Virginia','Virginia'],['Washington','Washington'],['West Virginia','West Virginia'],['Wisconsin','Wisconsin'],['Wyoming','Wyoming']]) %>
  </p>

    </div>
    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
 
	  <p class="ex1">
	    <%= form.label :Username %><br>
	    <%= form.text_field :username %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Confirm_Username %><br>
	    <%= form.text_field :username_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :Password %><br>
	    <%= form.password_field :password %>
	  </p>
	  
	  <p class="ex1">
	    <%= form.label :Confirm_Password %><br>
	    <%= form.password_field :password_confirmation %>
	  </p>

	  <p class="ex1">
	    <%= form.label :email %><br>
	    <%= form.email_field :email, placeholder:"example@website.com" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number, placeholder:"Ex: 956456789" %>
	  </p>
	
	  <p class="ex1">
	    <%= form.label :Phone_number %><br>
	    <%= form.telephone_field :phone_number_confirmation, placeholder:"Ex: 956456789" %>
	  </p>
  	  <p class="ex1">
  	    <%= form.submit 'Update User'%>
  	  </p>
    </div>
    <div class="col1"></div>

<% end %>
</div>
<footer> 
</footer>
</body>
</html>

era_website/app/views/govtusers/edit.html.erb
<style> p.ex1 {padding-left: 20px;}</style>
<%= render 'form1' %>
<%= link_to 'Back to profile', govtuser_path(current_user) %>

era_website/app/views/govtusers/index.html.erb
<head>
<style>
table, th, td {
    border: 2px solid black;
    padding: 8px;
}
tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>
<h1 style="text-align:center"> All Users: Admin Use Only </h1>
<h4>
<p style="padding-left: 20px;">
<%= link_to 'Back to profile', govtuser_path(current_user) %><br>
</p>

<table align="center" style="width:95%">
  <caption>Government Users</caption>
  <tr>
    <th style="width:15%">Username</th>
    <th style="width:20%">Name</th>
    <th style="width:20%">Organization</th>
    <th style="width:25%" colspan="3"></th> 
  </tr>
 
  <% @govtusers.where(usertype: 'govt').each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td><%= user.orgname %></td>    
  <!--    <td style="text-align: center"><%= link_to 'Show', govtuser_path(user) %></td>
      <td style="text-align: center"><%= link_to 'Profile', govtuser_path(user) %></td>  -->
      <td style="text-align: center"><%= link_to 'Delete', govtuser_path(user),
				method: :delete,
				data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>
<br><br>
<table align="center" style="width:95%">
  <caption>Civilian Users</caption>
  <tr>
    <th style="width:15%">Username</th>
    <th style="width:20%">Name</th>
    <th style="width:20%">City</th>
    <th style="width:20%">State</th>
    <th style="width:25%" colspan="2"></th> 
  </tr>
 
  <% @govtusers.where(usertype: 'civil').each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %> <%= user.last_name %></td>
      <td><%= user.city %></td>
      <td><%= user.state %></td>
     <!-- <td style="text-align: center"><%= link_to 'Show', govtuser_path(user) %></td> -->
      <td style="text-align: center"><%= link_to 'Delete', govtuser_path(user),
				method: :delete,
				data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>
</body>
</h4>

era_website/app/views/govtusers/login.html.erb
<% provide(:title, 'Login') %>
<h1>Login</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

era_website/app/views/govtusers/new.html.erb
<style> p.ex1 {padding-left: 20px;}</style>
<%= render 'form' %>
<p class="ex1"><%= link_to 'Return to Welcome Page', controller: 'welcome' %></p>

era_website/app/views/govtusers/profile.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
User Profile<hr>
</header>

<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">
          <h3>Profile Information</h3>
          <ul>
            <li class="ex2"> <strong>Username: </strong><%= @govtuser.username %></li>
            <li class="ex2"> <strong>Name: </strong><%= @govtuser.first_name %> <%= @govtuser.last_name %></li>
            <li class="ex2"> <strong>Street Address: </strong><%= @govtuser.address %></li>
            <li class="ex2"> <strong>City: </strong><%= @govtuser.city %></li>
            <li class="ex2"> <strong>State: </strong><%= @govtuser.state %></li><hr>
          </ul>   
    </div>

    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
            <h3>Contact Information</h3>        
	      <strong>Email:</strong><%= @govtuser.email %><br>
	      <strong>Phone Number:</strong><%= @govtuser.phone_number %>
    </div>
    <div class="col1"></div>

</div>

<footer> 
</footer>
</body>
</html>
  

era_website/app/views/govtusers/show.html.erb
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
    box-sizing: border-box;
}
body {
    font-family: Arial, Helvetica, sans-serif;
}
/* Style the header */
header {
    background-color: #0000cc;
    padding: 30px;
    text-align: center;
    font-size: 35px;
    color: white;
}
p.ex1 {padding-left: 20px;} li.ex2 {padding-left: 20px;}
/* Style the footer */
footer {
    background-color:#66a3ff;
    padding: 10px;
    text-align: center;

}

.col-container {
    display: table;
    width: 100%;
}
.col {
    display: table-cell;
	width:40%;
    padding: 16px;
}

.col1 {
    display: table-cell;
    width: 10%;
    padding: 16px;
}

@media only screen and (max-width: 1000px) {
    .col { 
        display: block;
        width: 100%;
    }
    .col1 { 
        display: block;
        width: 100%;
    }
}

</style>
</head>
<body>

<header>
Main Page<hr>
</header>

<div class="col-container">

    <div class="col1"></div>
    <div class="col" style="background: #ccc; font-size:20px; padding-left:20px;">
          <h3>Profile Information</h3>
          <ul>
            <li class="ex2"> <strong>Username: </strong><%= @govtuser.username %></li>
            <li class="ex2"> <strong>Name: </strong><%= @govtuser.first_name %> <%= @govtuser.last_name %></li>
            <li class="ex2"> <strong>Street Address: </strong><%= @govtuser.address %></li>
            <li class="ex2"> <strong>City: </strong><%= @govtuser.city %></li>
            <li class="ex2"> <strong>State: </strong><%= @govtuser.state %></li><hr>
            <% if current_user.username .eql? "Admin" %>
		<li class="ex2"> <%= link_to 'View All Disasters', controller: 'disasterevents' %></li>
		<li class="ex2"><%= link_to 'All Users', controller: 'govtusers' %></li>
	        <li class="ex2"><%= link_to 'Show all Government Organizations', controller: 'organizations' %></li>
		<li class="ex2"> <%= link_to 'Create Disaster Page', new_disasterevent_path %></li>
	    <% end %>
	    <% if current_user.usertype .eql? "govt" %>
	    	<li class="ex2"> <%= link_to 'Create Disaster Page', new_disasterevent_path %></li>
	    <% end %>
            <li class="ex2"> <%= link_to 'View Disasters', controller: 'disasterevents' %></li>
	    <li class="ex2"> <%= link_to 'Edit Profile', edit_govtuser_path(@govtuser) %></li>
	    <% if logged_in? %>
		<li class="ex2"> <%= link_to "Log out", logout_path, method: :delete %></li>
      	    <% end %>
          </ul>   
    </div>

    <div class="col" style="background: #f1f1f1; font-size:20px; padding-left:20px;">
            <h3>Contact Information</h3>        
	      <strong>Email:</strong><%= @govtuser.email %><br>
	      <strong>Phone Number:</strong><%= @govtuser.phone_number %>
    </div>
    <div class="col1"></div>

</div>

<footer> 
</footer>
</body>
</html>
  